### ISSUE TITLE
Not syncing with locize dashboard

### ISSUE THREAD

**Issue by simerdev** [locize/locizify#157]
I have added script tag in header but nothing is showing in my locize dashboard. There are no keys , no namespaces created. Is there any thing that I am missing. Please help me out.

**Comment by jamuhl** [comment]
Can you share some more informations?

Did you create a project and set projectId/apiKey?

**Comment by simerdev** [comment]
Yes, I have created Project and add projectId and apiKey, in the script. I have use this script
`<script id="locizify" projectid="bcc046f3-****-44a2-b367-07d7ff18ef7a" debug="false" apikey="de3b6fd5-3469-****-****-66dbceac18f3" saveMissing="true" referencelng="en" fallbacklng="en" src="https://unpkg.com/locizify@^2.0.0"></script>`

**Comment by jamuhl** [comment]
https://github.com/locize/locizify#via-init-function -> `allowedAddOrUpdateHosts`

setting `debug: true` might show you that without overriding the option above saveMissing is only allowed from localhost environment.
