### ISSUE TITLE
Using data-* attributes for locizify to avoid ESLint issues with custom script tag attributes

### ISSUE THREAD

**Issue by khashashin** [locize/locizify#160]
## 🚀 Feature Proposal

When using locizify, ESLint shows errors on custom attributes used to initialize the library. To avoid this issue and maintain HTML semantics, I propose modifying the custom attributes to be `data-*` attributes. This will eliminate conflicts with HTML semantics and prevent ESLint errors.

### Current Implementation

```html
<!DOCTYPE html>
<html>
  <head>
    <script
      id="locizify"
      projectid="[PROJECT_ID]"
      apikey="[API_KEY]"
      src="https://unpkg.com/locizify@^5.3.1"
      autopilot
    ></script>
  </head>
  ...
</html>
```

### Proposed Implementation

```html
<!DOCTYPE html>
<html>
  <head>
    <script
      id="locizify"
      data-projectid="[PROJECT_ID]"
      data-apikey="[API_KEY]"
      src="https://unpkg.com/locizify@^5.3.1"
      data-autopilot="true"
    ></script>
  </head>
  ...
</html>
```

## Motivation

The main motivation for this proposal is to eliminate the need to add eslint-ignore comments in projects using locizify. By using `data-*` attributes, we can maintain valid HTML syntax while also preventing unnecessary ESLint errors.

## Example

The example provided above demonstrates how the proposed implementation would be used in a typical HTML document. By changing custom attributes to `data-*` attributes, we can prevent ESLint errors and maintain valid HTML syntax.

**Comment by adrai** [comment]
v5.4.0 should address this

**Comment by ggcaponetto** [comment]
I can confirm this is working with data-* attributes after upgrading to v5.4.0. I would suggest to update the readme and docs too to be in line with best practices.
