### ISSUE TITLE
Extend the documentation with information about the namespace quantity limits

### ISSUE THREAD

**Issue by khashashin** [locize/locizify#161]
## 🚀 Feature Proposal

The documentation should include clear details about the maximum number of namespaces supported by locize. Currently, it is difficult to determine what the limit is, if any, without testing or guessing. Adding this information would help developers configure their setups efficiently.

## Motivation

When working with multiple namespaces for various projects or modules, it's important to know how many namespaces we can use without running into limitations. This information is essential for planning the architecture of i18n setups. It would prevent confusion and ensure that developers stay within the supported limits.

## Example

In the documentation, under the "Namespaces" section, there could be a note specifying the maximum number of namespaces allowed, for example:

> "The maximum number of namespaces allowed per project is X."

This will help teams understand how to structure their projects in accordance with any potential limitations.

**Comment by adrai** [comment]
Hi Yusuf,

Thank you for your proposal and for taking the time to provide detailed feedback.

Regarding your request, I’d like to clarify that there isn’t a fixed limit on the number of namespaces supported by locize and or i18next. The number of namespaces you can use is flexible and largely depends on how they are loaded and utilized within your project.

In practice, developers usually organize namespaces based on different UI sections or pages, loading them as needed. Here’s a general guideline based on common usage:

- Up to 10 namespaces: Most common usage scenario for small to medium-sized projects.
- 20-50 namespaces: Typically used in larger projects with more complex UI or feature sets.
- More than 50 namespaces: If you’re planning to use hundreds of namespaces, we recommend re-evaluating your approach. It might be beneficial to discuss this with us to ensure optimal performance and structure. You can reach out to our support team at [support@locize.com](mailto:support@locize.com) for a more tailored review of your setup.

We hope this helps to clarify things. If you have further questions or need assistance with your project, please don’t hesitate to reach out.

**Comment by khashashin** [comment]
Great, thanks for the clarification. We were discussing in the team about potential limitations on the number of namespaces in relation to our project structuring, as we’re looking at around 2,200 namespaces. However, it's reassuring to know that there isn’t a strict limit. Thanks again for the prompt response!
